"""A single question asked within an InterviewRound. Generated by that
round's agent (TechnicalAgent, CodingAgent, BehaviorAgent, ...) — the
agent's structured output schema is the source of truth for `metadata`'s
shape (e.g. a coding question's metadata carries starter code + test
cases; a behavioral question's carries the STAR dimension it targets)."""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.answer import Answer
    from app.models.interview_round import InterviewRound


class Question(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "questions"

    round_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("interview_rounds.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    order_index: Mapped[int] = mapped_column(Integer, nullable=False)
    difficulty: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # Agent-specific structured extras — starter code/test cases for a
    # coding question, target competency for a behavioral one, etc.
    question_metadata: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    round: Mapped[InterviewRound] = relationship(back_populates="questions")
    answers: Mapped[list[Answer]] = relationship(
        back_populates="question", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Question id={self.id} order={self.order_index}>"
